/* SPDX-License-Identifier: LGPL-2.1-or-later */
/*
 * va_test.c — VA-API decode correctness test for rockchip-vaapi
 *
 * Reads an IVF/VP9 file, decodes it via our driver, and verifies that each
 * exported frame has the expected luma value at (0,0).  Use with a synthetic
 * video where frame N has uniform luma = N*8 (generated by ffmpeg geq filter).
 *
 * Build:
 *   gcc -O1 -o va_test src/va_test.c -lva -lva-drm -ldrm -I/usr/include/libdrm
 *
 * Usage:
 *   ./va_test /tmp/test_vp9.ivf
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/ioctl.h>

#include <va/va.h>
#include <va/va_drm.h>
#include <va/va_drmcommon.h>

/* ── IVF format ──────────────────────────────────────────────────────────── */

typedef struct __attribute__((packed)) {
    uint8_t  sig[4];        /* "DKIF" */
    uint16_t version;
    uint16_t hdr_len;
    uint32_t fourcc;        /* 'VP90' */
    uint16_t width;
    uint16_t height;
    uint32_t fps_num;
    uint32_t fps_den;
    uint32_t nframes;
    uint32_t rsvd;
} IvfFileHeader;

typedef struct __attribute__((packed)) {
    uint32_t size;
    uint64_t pts;
} IvfFrameHeader;

/* ── VP9 header helpers ──────────────────────────────────────────────────── */

static int vp9_is_keyframe(const uint8_t *d, size_t len)
{
    if (!d || len < 1) return 1;
    uint8_t b = d[0];
    if ((b >> 6) != 2) return 1;
    int profile = ((b >> 5) & 1) | (((b >> 4) & 1) << 1);
    if (profile != 3) {
        if ((b >> 3) & 1) return 0;  /* show_existing_frame — not a keyframe */
        return !((b >> 2) & 1);      /* frame_type: 0=key */
    } else {
        if ((b >> 2) & 1) return 0;
        return !(b & 1);
    }
}

static int vp9_show_frame(const uint8_t *d, size_t len)
{
    if (!d || len < 1) return 1;
    uint8_t b = d[0];
    if ((b >> 6) != 2) return 1;
    int profile = ((b >> 5) & 1) | (((b >> 4) & 1) << 1);
    if (profile != 3) {
        if ((b >> 3) & 1) return 1;   /* show_existing_frame → shown */
        return (b >> 1) & 1;          /* show_frame */
    } else {
        if ((b >> 2) & 1) return 1;
        return b & 1;
    }
}

/* ── Main test ───────────────────────────────────────────────────────────── */

#define N_SURFACES  8
#define CHECK_VA(call) do {                                         \
    VAStatus _s = (call);                                           \
    if (_s != VA_STATUS_SUCCESS) {                                  \
        fprintf(stderr, "VA error %d at %s:%d: %s\n",              \
                _s, __FILE__, __LINE__, vaErrorStr(_s));            \
        return 1;                                                   \
    }                                                               \
} while (0)

int main(int argc, char **argv)
{
    if (argc < 2) {
        fprintf(stderr, "Usage: %s test.ivf\n", argv[0]);
        return 1;
    }

    /* ── Open IVF ── */
    FILE *ivf = fopen(argv[1], "rb");
    if (!ivf) { perror(argv[1]); return 1; }

    IvfFileHeader fh;
    if (fread(&fh, sizeof(fh), 1, ivf) != 1 ||
        memcmp(fh.sig, "DKIF", 4) != 0) {
        fprintf(stderr, "Not an IVF file\n");
        return 1;
    }
    int width  = fh.width;
    int height = fh.height;
    int nframes = fh.nframes;
    printf("IVF: %dx%d, %d frames, codec=%c%c%c%c\n",
           width, height, nframes,
           (char)(fh.fourcc), (char)(fh.fourcc>>8),
           (char)(fh.fourcc>>16), (char)(fh.fourcc>>24));

    /* ── Open DRM / VA ── */
    int drm_fd = open("/dev/dri/renderD128", O_RDWR);
    if (drm_fd < 0) { perror("/dev/dri/renderD128"); return 1; }

    VADisplay dpy = vaGetDisplayDRM(drm_fd);
    if (!dpy) { fprintf(stderr, "vaGetDisplayDRM failed\n"); return 1; }

    int major, minor;
    CHECK_VA(vaInitialize(dpy, &major, &minor));
    printf("VA-API %d.%d\n", major, minor);

    /* ── Create config (VP9 Profile 0) ── */
    VAConfigID cfg = VA_INVALID_ID;
    CHECK_VA(vaCreateConfig(dpy, VAProfileVP9Profile0,
                            VAEntrypointVLD, NULL, 0, &cfg));

    /* ── Create surfaces ── */
    VASurfaceID surfs[N_SURFACES];
    {
        VASurfaceAttrib attribs[2] = {
            { .type = VASurfaceAttribPixelFormat, .flags = VA_SURFACE_ATTRIB_SETTABLE,
              .value = { .type = VAGenericValueTypeInteger,
                         .value.i = VA_FOURCC_NV12 } },
            { .type = VASurfaceAttribUsageHint, .flags = VA_SURFACE_ATTRIB_SETTABLE,
              .value = { .type = VAGenericValueTypeInteger,
                         .value.i = VA_SURFACE_ATTRIB_USAGE_HINT_DECODER } }
        };
        CHECK_VA(vaCreateSurfaces(dpy, VA_RT_FORMAT_YUV420,
                                  width, height, surfs, N_SURFACES,
                                  attribs, 2));
    }

    /* ── Create context ── */
    VAContextID ctx = VA_INVALID_ID;
    CHECK_VA(vaCreateContext(dpy, cfg, width, height,
                             VA_PROGRESSIVE, surfs, N_SURFACES, &ctx));

    /* ── Decode loop ── */
    uint8_t *frame_buf = NULL;
    size_t   frame_cap = 0;
    int surf_idx = 0;
    int errors = 0;

    for (int fn = 0; fn < nframes; fn++) {
        IvfFrameHeader frhdr;
        if (fread(&frhdr, sizeof(frhdr), 1, ivf) != 1) {
            fprintf(stderr, "Truncated IVF at frame %d\n", fn);
            break;
        }
        uint32_t sz = frhdr.size;
        if (sz > frame_cap) {
            frame_buf = realloc(frame_buf, sz);
            frame_cap = sz;
        }
        if (fread(frame_buf, 1, sz, ivf) != sz) {
            fprintf(stderr, "Truncated frame %d\n", fn);
            break;
        }

        int shown  = vp9_show_frame(frame_buf, sz);
        int is_key = vp9_is_keyframe(frame_buf, sz);
        /* Only check luma for shown frames; wrap at 256 since geq uses N*8. */
        int expected_luma = (shown && fn < 256) ? ((fn * 8) & 0xFF) : -1;

        VASurfaceID surf = surfs[surf_idx % N_SURFACES];
        surf_idx++;

        /* BeginPicture */
        CHECK_VA(vaBeginPicture(dpy, ctx, surf));

        /* Submit only raw slice data — our driver ignores picture/slice params */
        VABufferID slice_buf = VA_INVALID_ID;
        CHECK_VA(vaCreateBuffer(dpy, ctx, VASliceDataBufferType,
                                sz, 1, frame_buf, &slice_buf));
        CHECK_VA(vaRenderPicture(dpy, ctx, &slice_buf, 1));
        CHECK_VA(vaEndPicture(dpy, ctx));
        CHECK_VA(vaDestroyBuffer(dpy, slice_buf));

        /* Sync */
        CHECK_VA(vaSyncSurface(dpy, surf));

        /* Export */
        VADRMPRIMESurfaceDescriptor desc = {0};
        VAStatus est = vaExportSurfaceHandle(dpy, surf,
                                             VA_SURFACE_ATTRIB_MEM_TYPE_DRM_PRIME_2,
                                             VA_EXPORT_SURFACE_READ_ONLY |
                                             VA_EXPORT_SURFACE_SEPARATE_LAYERS,
                                             &desc);

        int actual_luma = -1;
        if (est == VA_STATUS_SUCCESS && desc.num_objects > 0) {
            int exp_fd = desc.objects[0].fd;
            /* Y plane is first, offset 0.  Map just one row (or a small chunk). */
            size_t map_size = (size_t)desc.layers[0].pitch[0] * 16;
            if (map_size == 0) map_size = 4096;
            void *ptr = mmap(NULL, map_size, PROT_READ, MAP_SHARED, exp_fd, 0);
            if (ptr != MAP_FAILED) {
                actual_luma = ((uint8_t *)ptr)[0];
                munmap(ptr, map_size);
            }
            close(exp_fd);
        }

        const char *flag = "";
        if (!shown)  flag = " [altref/hidden]";
        if (is_key)  flag = " [KEYFRAME]";

        int ok = (expected_luma < 0) ||
                 (actual_luma >= 0 && abs(actual_luma - expected_luma) <= 4);
        if (!ok) errors++;

        printf("frame %2d: surf=0x%x  shown=%d  expected_luma=%3d  actual_luma=%3d  %s%s\n",
               fn, (unsigned)surf, shown,
               expected_luma, actual_luma,
               ok ? "OK" : "*** WRONG ***",
               flag);
        fflush(stdout);
    }

    printf("\n%s — %d errors in %d frames\n",
           errors ? "FAIL" : "PASS", errors, nframes);

    free(frame_buf);
    vaDestroyContext(dpy, ctx);
    for (int i = 0; i < N_SURFACES; i++) vaDestroySurfaces(dpy, &surfs[i], 1);
    vaDestroyConfig(dpy, cfg);
    vaTerminate(dpy);
    close(drm_fd);
    fclose(ivf);
    return errors ? 1 : 0;
}
